apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim
spec:
  storageClassName: viettq-nfs-delete
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi      
