apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: http-pod
  name: http-pod
spec:
  containers:
  - image: httpd:latest
    name: http-pod
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
