#ClusterRole: get-namespaces
#Permission: get namespaces
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: get-namespaces
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "watch", "list"]  
  

#ClusterRole: get-nodes
#Permission: get nodes
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: get-nodes
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "watch", "list"]  

#ClusterRole: get-persistentvolumes
#Permission: get persistentvolumes
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: get-persistentvolumes
rules:
- apiGroups: [""]
  resources: ["persistentvolumes"]
  verbs: ["get", "watch", "list"] 
  
#ClusterRole: get-ingressclasses
#Permission: get ingressclasses
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:  
  name: get-ingressclasses
rules:
- apiGroups: [""]  
  resources: ["ingressclasses"]
  verbs: ["get", "watch", "list"]   
  
#ClusterRole: get-storageclasses
#Permission: get storageclasses
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:  
  name: get-storageclasses
rules:
- apiGroups: [""]
  resources: ["storageclasses"]
  verbs: ["get", "watch", "list"]    
  
  ingressclasses